Import('*')

niflib_python = env.SharedLibrary('_niflib', 'niflib.i', LIBS=[niflib] + python_lib, LIBPATH = python_libpath, CPPPATH = ['.'] + python_include, SHLIBPREFIX='')
ninode_python = env.SharedLibrary('_ninode', 'ninode.i', LIBS=[niflib] + python_lib, LIBPATH = python_libpath, CPPPATH = ['.'] + python_include, SHLIBPREFIX='')

Return('niflib_python ninode_python')
